### ISSUE TITLE
[WebUI] Use Case: See Profile Details

### ISSUE THREAD

**Issue by CarinaKl** [mercedes-benz/sechub#1892] opened 2023-01-26 16:33 UTC
Users should be able to see their profile details. They need information about who is signed in, and further profile information. Information about possible support can be placed on this screen as well. There should be the possibility to change the password and to request a new API Token.

![Profileinstellungen](https://user-images.githubusercontent.com/122868367/214893229-f58b620d-e40b-421a-bb09-bed5bc9c6221.png)

**Comment by hamidonos** [comment] 2024-11-05 13:35
Duplicate of #3584

**Closed** 2024-11-05 13:34 UTC
Labels: web-ui
